export const FETCH_EPICS = 'FETCH_EPICS';
export const FETCH_TOPICS = 'FETCH_TOPICS';

export const RECEIVE_EPICS = 'RECEIVE_EPICS';
export const RECEIVE_TOPICS = 'RECEIVE_TOPICS';

export const UPDATE_TOPIC_DESCRIPTION = 'UPDATE_TOPIC_DESCRIPTION';
